/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/login/login" |
       "/pages/login/loginOauth2" |
       "/pages/user/people" |
       "/pages-user/location/location" |
       "/pages-user/organization/organization" |
       "/pages-user/userDetail/userDetail" |
       "/pages-user/userEdit/userEdit" |
       "/pages-study/course/courseList" |
       "/pages-study/course/detail" |
       "/pages-study/course/list" |
       "/pages-study/note/detail" |
       "/pages-study/note/list" |
       "/pages-study/note/wizard";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages-study/course/list" | "/pages/user/people"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
